version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5400:5400'
    expose:
      - '5400'
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    command: -p 5400
volumes:
  db:
    driver: local